# ****************************************
# * docker-compose.yml for i2b2 server   *
# * 環境変数は.envファイルに記入します        *
# ****************************************

services:
  # ––––––––––––––––––––––––––––––––––––––––––
  # i2b2 database (PostgreSQL)のコンテナ定義
  # ––––––––––––––––––––––––––––––––––––––––––
  # i2b2は`i2b2`という名前のデータベースを使用し、その中にCellごとのスキーマを作成するというのが基本構成です。
  i2b2-data-pgsql:
    build:
      context: ./postgres
      dockerfile: Dockerfile
      args:
        # i2b2 postgresのイメージタグ(バージョン)を指定。.envで指定した値が使われます。
        I2B2_DATA_PGSQL_TAG: ${I2B2_DATA_PGSQL_TAG}
    container_name: i2b2-data-pgsql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - I2B2_DB_NAME=${I2B2_DB_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_CONFIG_FILE=/var/lib/postgresql/data/postgresql.conf
    networks:
      - i2b2-net
    # Postgresのデータを永続化するためのDockerボリュームをマウントします
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ⚠️ Postgresのポート設定
    # (セキュリティ上の理由で公開しない、5432以外を使用するなどの場合、ここを変更してください。)
    ports:
      - 5432:5432

  # ––––––––––––––––––––––––––––––––––––––––––––––
  # i2b2 backend coreサーバーのコンテナ定義
  # ––––––––––––––––––––––––––––––––––––––––––––––
  i2b2-core-server:
    image: i2b2/i2b2-core-server:${I2B2_CORE_SERVER_TAG}
    container_name: i2b2-core-server
    restart: unless-stopped
    environment:
      # NOTE: ユーザーが変更することを想定しない環境変数は.envでなく、ここで指定しています。
      # i2b2のデータベースタイプ (i2b2自体はmysqlやoracleも対応しますが、ここではpostgresを使用します。変更しないでください。)
      - DS_TYPE=postgres
      # CRC cellの設定
      - DS_CRC_IP=i2b2-data-pgsql # i2b2-data-pgsqlはPostgresコンテナのサービス名。docker network内で名前解決されます。
      - DS_CRC_PORT=${POSTGRES_PORT}
      - DS_CRC_USER=${POSTGRES_USER}
      - DS_CRC_PASS=${POSTGRES_PASSWORD}
      - DS_CRC_DB=${I2B2_DB_NAME}
      - DS_CRC_SCHEMA=i2b2demodata
      - I2B2_DS_CRC_DB_TYPE=pg
      # ONT cellの設定
      - DS_ONT_IP=i2b2-data-pgsql
      - DS_ONT_PORT=${POSTGRES_PORT}
      - DS_ONT_USER=${POSTGRES_USER}
      - DS_ONT_PASS=${POSTGRES_PASSWORD}
      - DS_ONT_DB=${I2B2_DB_NAME}
      - DS_ONT_SCHEMA=i2b2metadata
      - I2B2_DS_ONT_DB_TYPE=pg
      # PM cellの設定
      - DS_PM_IP=i2b2-data-pgsql
      - DS_PM_PORT=${POSTGRES_PORT}
      - DS_PM_USER=${POSTGRES_USER}
      - DS_PM_PASS=${POSTGRES_PASSWORD}
      - DS_PM_DB=${I2B2_DB_NAME}
      - DS_PM_SCHEMA=i2b2pm
      - I2B2_DS_PM_DB_TYPE=pg
      # Hiveの設定
      - DS_HIVE_IP=i2b2-data-pgsql
      - DS_HIVE_PORT=${POSTGRES_PORT}
      - DS_HIVE_USER=${POSTGRES_USER}
      - DS_HIVE_PASS=${POSTGRES_PASSWORD}
      - DS_HIVE_DB=${I2B2_DB_NAME}
      - DS_HIVE_SCHEMA=i2b2hive
      - I2B2_DS_HIVE_DB_TYPE=pg
      # Workdataの設定
      - DS_WD_IP=i2b2-data-pgsql
      - DS_WD_PORT=${POSTGRES_PORT}
      - DS_WD_USER=${POSTGRES_USER}
      - DS_WD_PASS=${POSTGRES_PASSWORD}
      - DS_WD_DB=${I2B2_DB_NAME}
      - DS_WD_SCHEMA=i2b2workdata
    networks:
      - i2b2-net
    depends_on:
      - i2b2-data-pgsql

  # ––––––––––––––––––––––––––––––––––––––––––
  # i2b2-wbclientのコンテナ定義
  # ––––––––––––––––––––––––––––––––––––––––––
  i2b2-webclient:
    image: i2b2/i2b2-webclient:${I2B2_WEBCLIENT_TAG}
    container_name: i2b2-webclient
    restart: unless-stopped
    # WebClientのポート設定
    ports:
      - ${WEBCLIENT_PORT}:80"
    command: /run-httpd.sh localhost
    depends_on:
      - i2b2-core-server
    networks:
      - i2b2-net

# –––––––––––––––––––––––––––––––––––––––
# Docker Network 定義
# –––––––––––––––––––––––––––––––––––––––
networks:
  i2b2-net:
    name: i2b2-net
    driver: bridge

# –––––––––––––––––––––––––––––––––––––––
# Docker Volume 定義
# –––––––––––––––––––––––––––––––––––––––
volumes:
  # ⚠️ PostgresのデータはこのDockerボリュームに保存されます。
  pgdata:
    driver: local
