name: Build and Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  # 以下権限は通常不要。必要なら追加してください。
  # pages: write
  # id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Pythonのセットアップ (Sphinxを使うため。)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      # ドキュメンテーションをビルドするための依存関係をインストール (Sphinxを使います。)
      - name: Install docs dependencies
        run: |
          pip install sphinx sphinx-rtd-theme myst-parser

      # ドキュメンテーションのビルド
      - name: Build docs
        run: |
          cd docs
          make clean html

      # Jekyllを無効化 (GitHub Pagesのデフォルト動作を防ぐため)
      - name: Disable Jekyll
        run: touch docs/build/html/.nojekyll

      # GitHub Pagesにデプロイ (ブランチはgh-pagesを使用)
      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
          force_orphan: true
          commit_message: "docs: deploy ${{ github.sha }}"
